### ISSUE TITLE
Remove node-sass dependency

### ISSUE THREAD

**Issue by matthiaskomarek** [meodai/dialog-size#13]
Currently the `node-sass` package is a `dependency` and a `devDependency` in the `package.json`.
I think it doesn't need to be a `dependency` or at least the dependency should be updated to a newer node-sass version.
Because the current version `4.7.2` has no precompiled binaries for linux available.

**Comment by meodai** [comment]
@matthiaskomarek this was finally resolved. https://github.com/meodai/dialog-size/commit/52daf9cd1a5719547decc685885d227f99074f2e
